export const CERTIFIED_PLUMBER = 'CERTIFIED_PLUMBER';
export const CARPENTRY_EXPERIENCE = 'CARPENTRY_EXPERIENCE';
export const CERTIFIED_ELECTRICIAN = 'CERTIFIED_ELECTRICIAN';
export const BARTENDING_EXPERIENCE = 'BARTENDING_EXPERIENCE';
export const FOOD_HYGIENE = 'FOOD_HYGIENE';
export const FIRST_AID = 'FIRST_AID';
export const FORKLIFT_DRIVE = 'FORKLIFT_DRIVE';
export const DRIVERS_LICENCE = 'DRIVERS_LICENCE';
